In [ ]:
from loguru import logger

logger.info('info')
logger.warning('warning')
logger.error('error')

In [5]:
import numpy as np
import json

class Test:
    def __init__(self, test, name):
        self.test = test
        self.name = name
    # image = np.zeros((100, 100, 3))

print(Test.__name__)
test = Test(1, 'test')
print(test.__dict__)
a = Test(**test.__dict__)
print(getattr(a, 'name'))
print(a)
print(Test.__name__)
print(isinstance(a, Test))

json_str = json.dumps(test.__dict__)
print(json_str)

Test
{'test': 1, 'name': 'test'}
test
Test
True
{"test": 1, "name": "test"}


In [56]:
import numpy as np
from multiprocessing import shared_memory

hwc = (3, 3, 3)
qsize = 10
shape = [qsize] + list(hwc)
print(shape)

size = np.prod(hwc) * qsize
# initialize shared memory
name = 'test_shared_memory'
sm_w = shared_memory.SharedMemory(name = name, size = size, create=False)
# sm_w.close()
# sm_w.unlink()
image_w = np.ndarray(shape, dtype=np.uint8, buffer=sm_w.buf)
print(sm_w)

sm_r = shared_memory.SharedMemory(name = name, size = size, create=False)
image_r = np.ndarray(shape, dtype=np.uint8, buffer=sm_r.buf)
print(sm_r)

img = np.random.randint(128, size=hwc, dtype=np.uint8)
print(img)
image_w[9] = img.data

print('==================')
print(image_r[9])

# sm_r.close()
# sm_r.unlink()

[10, 3, 3, 3]
SharedMemory('test_shared_memory', size=270)
SharedMemory('test_shared_memory', size=270)
[[[112  39  56]
  [  8  40  79]
  [ 46  39  21]]

 [[  9  23   5]
  [ 53  95  27]
  [121  72  61]]

 [[ 86  40 127]
  [ 57   5 110]
  [ 68 110  54]]]
[[[112  39  56]
  [  8  40  79]
  [ 46  39  21]]

 [[  9  23   5]
  [ 53  95  27]
  [121  72  61]]

 [[ 86  40 127]
  [ 57   5 110]
  [ 68 110  54]]]


In [5]:
(12+1) % 20

13