In [1]:
import torch
import torchvision
import torch.nn as nn
import torchvision.transforms as transforms
import numpy as np

In [5]:
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

y = w * x + b # y = 2x + 3

# compute gradients
y.backward()
print(x.grad) # dy/dx = w = 2
print(w.grad) # dy/dw = x = 1
print(b.grad) # dy/db = 1

tensor(2.)
tensor(1.)
tensor(1.)


In [38]:
x = torch.randn(1000, 1)
y = 2 * x + 1
print(x.shape, y.shape)

# build a fully connected layer
linear = nn.Linear(1, 1)
print('w', linear.weight)
print('b', linear.bias)

# build loss function and optimizer
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(linear.parameters(), lr=0.01)

for i in range(1000):
    optimizer.zero_grad()
    # forward pass
    pred = linear(x)
    # compute loss
    loss = criterion(pred, y)
    # print('loss', loss.item())

    # backward pass
    loss.backward()
    # print('dL/dw', linear.weight.grad)
    # print('dL/db', linear.bias.grad)

    # 1-step gradient descent
    optimizer.step()

pred = linear(x)
loss = criterion(pred, y)
print('dL/dw', linear.weight.grad)
print('dL/db', linear.bias.grad)
print('weight', linear.weight)
print('bias', linear.bias)
print('loss after 1 step optimization: ', loss.item())

import numpy as np
test = np.array([1.], dtype=np.float32)
test = torch.from_numpy(test)
print(test)
linear.eval()
linear(test)

torch.Size([1000, 1]) torch.Size([1000, 1])
w Parameter containing:
tensor([[-0.5448]], requires_grad=True)
b Parameter containing:
tensor([-0.8652], requires_grad=True)
dL/dw tensor([[-0.0001]])
dL/db tensor([-2.2173e-06])
weight Parameter containing:
tensor([[1.9999]], requires_grad=True)
bias Parameter containing:
tensor([1.0000], requires_grad=True)
loss after 1 step optimization:  2.808755228400628e-09
tensor([1.])


tensor([2.9999], grad_fn=<AddBackward0>)

In [2]:
x = np.array([[1, 2], [3, 4]])
y = torch.from_numpy(x)
z = y.numpy()
print(x)
print(y)
print(z)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]


In [ ]:
# Download and construct CIFAR-10 dataset
train_dataset = torchvision.datasets.CIFAR10(
    root='data', train=True, transform=transforms.ToTensor(),
    download=True)